apiVersion: v1
kind: Service
metadata:
  name: serviciofeliz
spec:
  selector:
    app: kubeoperations
  ports:
    - port: 80 #Es el puerto por defecto el localhost
      targetPort: 8080
  type: LoadBalancer #Balancea la carga en mis pods

---
#Manifest0
apiVersion: apps/v1
kind: Deployment #Pensado para muchos deployments
metadata:
  name: deployfeliz
spec:
  replicas: 10
  selector: #Para seleccionar que crear
    matchLabels:
      app: kubeoperations
  template:
    metadata:
      labels:
        app: kubeoperations
    spec:
      containers:
        - name: contenedorkuboso
          image: lulikwerner/operaciones:1.0.0
          ports:
            - containerPort: 8080 
          imagePullPolicy: Always

